# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import logging
import os, re
from abc import ABC, abstractmethod

import regex
from pydantic import BaseModel

from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class FunctionCall(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ToolParser(ABC):
    _registry: dict[str, type["ToolParser"]] = {}

    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer

    @abstractmethod
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        """Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.

        Returns:
            Tuple[str, List[FunctionCall]]: Content and extracted tool calls.
        """
        raise NotImplementedError

    @classmethod
    def get_tool_parser(cls, name: str, tokenizer):
        if name not in cls._registry:
            raise ValueError(f"Unknown tool parser: {name}")
        return cls._registry[name](tokenizer)

    @classmethod
    def register(cls, name: str):
        def decorator(subclass: type[ToolParser]) -> type[ToolParser]:
            cls._registry[name] = subclass
            return subclass

        return decorator


@ToolParser.register("hermes")
class HermesToolParser(ToolParser):
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.tool_call_regex = regex.compile(r"<tool_call>(.*?)</tool_call>", regex.DOTALL)

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        if self.tool_call_start_token not in text or self.tool_call_end_token not in text:
            return text, []

        matches = self.tool_call_regex.findall(text)
        function_calls = []
        for match in matches:
            try:
                function_call = json.loads(match)
                name, arguments = function_call["name"], function_call["arguments"]
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
            except Exception as e:
                logger.error(f"Failed to decode tool call: {e}")

        # remaing text exclude tool call tokens
        content = self.tool_call_regex.sub("", text)
        return content, function_calls


@ToolParser.register("gpt-oss")
class GptOssToolParser(ToolParser):
    """
    Tool parser for gpt-oss model.
    Adapted from https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/function_call/gpt_oss_detector.py

    Args:
        tokenizer: The tokenizer to use.
    """

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)
        # check https://cookbook.openai.com/articles/openai-harmony for more details.
        self.cot_pattern = regex.compile(
            r"<\|start\|>assistant<\|channel\|>analysis<\|message\|>.*?<\|end\|>", regex.DOTALL
        )
        # <|start|>assistant may be pre-appended in prompts, so we need to remove it.
        self.partial_cot_pattern = regex.compile(r"<\|channel\|>analysis<\|message\|>(.*?)<\|end\|>", regex.DOTALL)
        self.tool_call_pattern = regex.compile(
            r"<\|start\|>assistant<\|channel\|>[^<]* to=functions\.([^<]+) "
            r"<\|constrain\|>json<\|message\|>(.*?)<\|call\|>",
            regex.DOTALL,
        )

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        loop = asyncio.get_running_loop()
        # We need to keep special tokens for gpt-oss model for better tool call extraction.
        text = await loop.run_in_executor(None, lambda: self.tokenizer.decode(responses_ids, skip_special_tokens=False))
        # Need to remove padding tokens for better tool call extraction.
        text = text.replace(self.tokenizer.pad_token, "")
        # Need to reomve COT since COT may contain tool call tokens.But they are not valid tool calls.
        text = regex.sub(self.cot_pattern, "", text)
        text = regex.sub(self.partial_cot_pattern, "", text)

        # check if there are tool calls in the text by re.findall
        matches = regex.findall(self.tool_call_pattern, text)
        if not matches:
            return text, []

        function_calls = []
        for match in matches:
            try:
                name, arguments = match[0], match[1]
                # don't check if arguments is valid JSON and leave it to client
                function_calls.append(FunctionCall(name=name, arguments=arguments))
            except Exception as e:
                logger.error(f"Failed to decode tool call: {e}")

        # remaing text exclude tool call tokens
        content = regex.sub(self.tool_call_pattern, "", text)

        return content, function_calls


# add custom tool parser
@ToolParser.register("custom")
class CustomToolParser(ToolParser):
    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
    
    def parse_tool_call(self, text: str):
        """
            解析工具调用字符串。
            
            输入示例: "<tool_call>{\"name\":\"google_search\",\"arguments\":{\"query_list\":[\"current weather in Tokyo\"]}}</tool_call>"
            输出示例: {
                "name": "google_search",
                "arguments": {"query_list": ["current weather in Tokyo"]}
            }
            
            如果格式不匹配，返回 None。
        """
        if not isinstance(text, str):
            return None

        text = text.strip()
        if not text:
            return None
        # 优先解析标准 JSON tool call：<tool_call>{...}</tool_call>
        pattern = r'<tool_call>\s*(\{.*?\})\s*</tool_call>'
        match = re.fullmatch(pattern, text, flags=re.DOTALL)
        if match:
            try:
                payload = json.loads(match.group(1))
                if not isinstance(payload, dict):
                    return None
                if payload.get("name") != "google_search":
                    return None
                arguments = payload.get("arguments", {})
                if not isinstance(arguments, dict):
                    return None
                query_list = arguments.get("query_list", [])
                if not isinstance(query_list, list):
                    return None
                cleaned_queries = [q.strip() for q in query_list if isinstance(q, str) and q.strip()]
                if not cleaned_queries:
                    return None
                return {
                    "name": "google_search",
                    "arguments": {
                        "query_list": cleaned_queries
                    }
                }
            except json.JSONDecodeError:
                return None

        # 兼容旧格式
        legacy_pattern = r'<google_search>\s*(.*?)\s*</google_search>'
        legacy_match = re.fullmatch(legacy_pattern, text, flags=re.DOTALL)
        if not legacy_match:
            return None

        query = legacy_match.group(1).strip()
        if not query:
            return None
        return {
            "name": "google_search",
            "arguments": {
                "query_list": [query]
            }
        }

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        
        has_json_tool_call = self.tool_call_start_token in text and self.tool_call_end_token in text
        has_legacy_tool_call = "<google_search>" in text and "</google_search>" in text
        if not has_json_tool_call and not has_legacy_tool_call:
            return text, []

        # 查找首个工具调用起点（新格式优先）
        first_match = re.search(r'<tool_call>|<google_search>', text)
        
        if first_match is None:
            # 没有找到任何工具调用，整个 text 都是 content，tool_calls 为空
            return text, []
        
        split_index = first_match.start()
        content = text[:split_index]
        
        # 从第一个工具调用开始的位置截取剩余部分
        remaining = text[split_index:]

        # 同时支持 <tool_call>...</tool_call> 与旧格式 <google_search>...</google_search>
        pattern = r'<tool_call>\s*.*?\s*</tool_call>|<google_search>\s*.*?\s*</google_search>'
        matches = re.findall(pattern, remaining, flags=re.DOTALL)
        
        tool_calls = []
        for match_str in matches:
            # print(match_str)
            parsed = self.parse_tool_call(match_str)
            if parsed is not None:
                name, arguments = parsed["name"], parsed["arguments"]
                tool_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
        
        return content.strip(), tool_calls
